### ISSUE TITLE
SemVer releases?

### ISSUE THREAD

**Issue by mattfarina** [gosuri/uitable#11]
Any chance of getting [SemVer](http://semver.org/) releases for this package? This would be useful for some of the tools consuming or otherwise scanning this library.

**Comment by trivigy** [comment]
Would appreciate if someone with contributor access could help out on this one. This post is from 2016.

**Comment by ahmetb** [comment]
@trivigy consider using https://github.com/olekukonko/tablewriter which is actively maintained.

**Comment by trivigy** [comment]
@ahmetb tablewriter doesn't do formatting correctly in a multi-column with different size multiline yaml prints in each column.

**Comment by trivigy** [comment]
@gosuri any chance to help out with this repository somehow? I will gladly create the semantic releases if I could.

**Comment by gosuri** [comment]
hey @trivigy, i just added a release - hope that helps

**Comment by trivigy** [comment]
That's awesome. Thank you.
