### ISSUE TITLE
Update table with response.

### ISSUE THREAD

**Issue by KeizerDev** [gosuri/uitable#9]
How can I update my table when fetching some information from any web source.
For example:

```
1    -   -
2    -   -
```

Should turn into

```
1  bar   foo
2  Foo   bar
```

Is this possible with the current lib?

**Comment by gosuri** [comment]
In realtime? use it along with uilive -- http://github.com/gosuri/uilive

**Comment by KeizerDev** [comment]
Yes. That's actually what I needed! Thanks!
